# NEEDS REPLACED WITH BRIANS IMAGE
FROM public.ecr.aws/e2j5x1k4/builds:maven as build

# Set the working directory in the container
WORKDIR /app

# Copy the local Maven files to the container
COPY . /app/

# Use Maven to build the application
RUN mvn clean install -DskipTests

# NEEDS REPLACED WITH BRIANS IMAGE
FROM public.ecr.aws/e2j5x1k4/builds:java

WORKDIR /app

# Copy the built jar file to the working directory in the container
COPY --from=build /app/target/*.jar /app/app.jar

# Run the application
ENTRYPOINT ["java", "-jar", "/app/app.jar"]