apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: default
spec:
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: eureka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: public.ecr.aws/e2j5x1k4/eureka:latest
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: eureka-service.default.svc.cluster.local
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
            - name: EUREKA_SERVER_WAIT_TIME_IN_MS_WHEN_SYNC_EMPTY
              value: "0"
