# Use the official Maven image from Docker Hub as the build stage
FROM public.ecr.aws/e2j5x1k4/builds:maven as build

# Set the working directory in the container
WORKDIR /app

# Copy the local Maven files to the container
COPY . /app/

# Use Maven to build the application
RUN mvn clean install -DskipTests

# Use the official OpenJDK image from Docker Hub for the final image
FROM public.ecr.aws/e2j5x1k4/builds:java

WORKDIR /app

# Copy the built jar file to the working directory in the container
COPY --from=build /app/target/*.jar /app/app.jar

# Run the application
ENTRYPOINT ["java", "-jar", "/app/app.jar"]