# NEEDS REPLACED WITH BRIANS IMAGE
FROM maven:3.8.4-openjdk-17 as build

# Set the working directory in the container
WORKDIR /app

# Copy the local Maven files to the container
COPY . /app/

# Use Maven to build the application
RUN mvn clean install -DskipTests

# NEEDS REPLACED WITH BRIANS IMAGE
FROM openjdk:17-jdk-slim

WORKDIR /app

# Copy the built jar file to the working directory in the container
COPY --from=build /app/target/*.jar /app/app.jar

# Run the application
ENTRYPOINT ["java", "-jar", "/app/app.jar"]