app:
  redirectUrl: https://frontend.aws-tfbd.com #changed
  logoutUrl: https://frontend.aws-tfbd.com
  origin: https://frontend.aws-tfbd.com


server:
  port: 8125

eureka:
  client:
    registerWithEureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service.default.svc.cluster.local/eureka/ # make sure this matches with eureka server name, the same as the DNS name in the cluster
  instance:
    preferIpAddress: true

spring:
  security:
    oauth2:
      client:
        registration:
          cognito: # fill in these values once cognito is created
            provider: cognito
            clientId: 2d3svka6127sau8iqv81qqu0us
            clientSecret: 1svdg13925sq2j9jk9nbb1qafeibuv11f63l8ukem6opgv97fc4i
            scope: openid,email,profile
            redirect-uri: https://api.aws-tfbd.com/login/oauth2/code/cognito
            #https://frontend.bgomes.aws-tfbd.com/auth/login/oauth2/code/cognito
            clientName: skillvest-cognito
            authorization-grant-type: authorization_code
        provider:
          cognito: # these values are related to the app client
            authorization-uri: https://tfbd.auth.us-east-1.amazoncognito.com/oauth2/authorize
            token-uri: https://tfbd.auth.us-east-1.amazoncognito.com/oauth2/token
            jwk-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_Ne5xAWeWT/.well-known/jwks.json # this value can be found in app client -> token signing key url
            user-info-uri: https://tfbd.auth.us-east-1.amazoncognito.com/oauth2/userInfo
            issuerUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_Ne5xAWeWT
            user-name-attribute: cognito:username

  application:
    name: gateway
  cloud:
    gateway:
      # probably not needed
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        # probably not needed
        add-to-simple-url-handler-mapping: "true"
        cors-configurations:
          '[/**]':
            allowedOrigins: "https://frontend.aws-tfbd.com" #changed
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes: # these routes must coorespond with eureka names that are set in Eureka, the service mesh is allowing that routing to happen
        - id: planner-service
          uri: lb://planner-service
          predicates:
            - Path=/planner/**, /goals/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallbackController

                fallbackUri: forward:/cache/planner  
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/accounts/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallbackController

                fallbackUri: forward:/cache/accounts
        - id: tax-service
          uri: lb://tax-service
          predicates:
            - Path=/taxes/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallbackController

                fallbackUri: forward:/cache/tax
        - id: investments
          uri: lb://investments
          predicates:
            - Path=/investments/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallbackController

                fallbackUri: forward:/cache/investments
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
