app:
  redirectUrl: https://frontend.skillstormcloud.com #must match naming convention
  logoutUrl: https://frontend.skillstormcloud.com
  origin: https://frontend.skillstormcloud.com

server:
  port: 8125

eureka:
  client:
    registerWithEureka: true
    fetch-registry: true
    service-url:
#      defaultZone: ${EUREKA_URI:http://host.docker.internal:8761/eureka/}
      defaultZone: http://eureka.default.svc.cluster.local/eureka # make sure this matches with eureka server name
  instance:
    preferIpAddress: true

spring:
  security:
    oauth2:
      client:
        registration:
          cognito: # fill in these values once cognito is created
            provider: cognito
            clientId: 1ci038800mova12nr2es3aied8
            clientSecret: 14kptrj6tu9jdfe7iqcek0nsbhuraaghv6nrgeccm0od582m25an
            scope: openid,email,profile
            redirect-uri: https://api.skillstormcloud.com/login/oauth2/code/cognito
#            redirect-uri: http://localhost:8125/login/oauth2/code/cognito
            clientName: SkillVest
            authorization-grant-type: authorization_code
        provider: # these values are related to the app client
          cognito:
            authorization-uri: https://skillvest.auth.us-east-1.amazoncognito.com/oauth2/authorize
            token-uri: https://skillvest.auth.us-east-1.amazoncognito.com/oauth2/token
            jwk-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_eApDJ2Jsu/.well-known/jwks.json # this value can be found in app client -> token signing key url
            user-info-uri: https://skillvest.auth.us-east-1.amazoncognito.com/oauth2/userInfo
            issuerUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_eApDJ2Jsu
            user-name-attribute: cognito:username

  application:
    name: gateway
  cloud:
    gateway:
      # probably not needed
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        # probably not needed
        add-to-simple-url-handler-mapping: "true"
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173" #change this also (in prod) 
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes: # these routes must coorespond with eureka names that are set in Eureka, the service mesh is allowing that routing to happen
        - id: planner-service
          uri: lb://planner-service
          predicates:
            - Path=/planner/**, /goals/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallbackController

                fallbackUri: forward:/cache/planner
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/accounts/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallbackController

                fallbackUri: forward:/cache/accounts
        - id: tax-service
          uri: lb://tax-service
          predicates:
            - Path=/taxes/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallbackController

                fallbackUri: forward:/cache/tax
        - id: investments
          uri: lb://investments
          predicates:
            - Path=/investments/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallbackController

                fallbackUri: forward:/cache/investments
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
