server:
  port: 8761 #standard port used for Eureka server

spring:
  application:
    name: skillvest
#Need to tell the eureka server to not register itself with itself
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
