app:
  redirectUrl: https://frontend.skillstormcloud.com
  logoutUrl: https://frontend.skillstormcloud.com
  origin: https://frontend.skillstormcloud.com


server:
  port: 8125

eureka:
  client:
    registerWithEureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka.default.svc.cluster.local/eureka/
  instance:
    preferIpAddress: true

spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            provider: cognito
            clientId: 5tmo2k20fvqilnip2ulgoj5cbv
            clientSecret: vldkj6pnmp3c8k9n8f7pom749n7hqs127buvgjpoj0e48phv54u
            scope: openid,email,profile
            redirect-uri: https://api.skillstormcloud.com/login/oauth2/code/cognito
            #https://frontend.bgomes.aws-tfbd.com/auth/login/oauth2/code/cognito
            clientName: SkillVest
            authorization-grant-type: authorization_code
        provider:
          cognito:
            authorization-uri: https://skillvest.auth.us-east-1.amazoncognito.com/oauth2/authorize
            token-uri: https://skillvest.auth.us-east-1.amazoncognito.com/oauth2/token
            jwk-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_2EO1Jous7/.well-known/jwks.json
            user-info-uri: https://skillvest.auth.us-east-1.amazoncognito.com/oauth2/userInfo
            issuerUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_2EO1Jous7
            user-name-attribute: cognito:username

  application:
    name: gateway
  cloud:
    gateway:
      # probably not needed
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        # probably not needed
        add-to-simple-url-handler-mapping: "true"
        cors-configurations:
          '[/**]':
            allowedOrigins: "https://frontend.skillstormcloud.com"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: planner-service
          uri: lb://planner-service
          predicates:
            - Path=/planner/**, /goals/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallbackController

                fallbackUri: forward:/cache/planner  
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/accounts/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallbackController

                fallbackUri: forward:/cache/accounts
        - id: tax-service
          uri: lb://tax-service
          predicates:
            - Path=/taxes/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallbackController

                fallbackUri: forward:/cache/tax
        - id: investments
          uri: lb://investments
          predicates:
            - Path=/investments/**
          filters:
            - name: CircuitBreaker
              args:
                name: fallbackController

                fallbackUri: forward:/cache/investments
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
