version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Updating apt-get...
      - apt-get update -y
      - echo Installing dependencies...
      - npm install npm@8.19.4
      - npm install typescript
      - npm install react react-dom react-router-dom

  build:
    commands:
      - echo Build started on `date`
      - npm run build      

  post_build:
    commands:
      - echo Uploading build artifacts to S3...
      - aws s3 cp --recursive dist s3://teamcuttlefish