# port config for gateway
server:
    port: 8082

spring:
    data:
        mongodb: #change
                uri: mongodb://teamcuttlefish:password@docdb-team-cuttlefish.cluster-cclvcxpivbxt.us-east-1.docdb.amazonaws.com:27017/?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
                database: skillvestDB
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER

    output:
        ansi:
            enabled: ALWAYS

    application:
        name: tax-service         # used as the id in the gateway routes


# configure where the discovery client is so our app can auto-register itself
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka.default.svc.cluster.local/eureka/} #change
  instance:
    preferIpAddress: true