apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8125
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: public.ecr.aws/e2j5x1k4/api:latest
          ports:
            - containerPort: 8125
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service.default.svc.cluster.local:8761/eureka/
            - name: EUREKA_INSTANCE_PREFERIPADDRESS
              value: "true"