version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo Updating yum...
      - yum update -y
      - echo Installing dependencies...
      - yum install -y curl
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - echo Logging in to Amazon ECR...
      - aws --version
      - export ECR_LOGIN_PASSWORD=$(aws ecr-public get-login-password --region us-east-1)
      - echo $ECR_LOGIN_PASSWORD | docker login --username AWS --password-stdin public.ecr.aws
      - REPOSITORY_URI=public.ecr.aws/e2j5x1k4/api #change 
      - echo Configuring kubectl...
      - aws eks update-kubeconfig --region us-east-1 --name team-cuttlefish-cluster

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - echo Docker image pushed successfully
      - echo Applying Kubernetes manifests...
      # - kubectl apply -f manifest.yaml
      # - echo Updating Kubernetes deployment...
      # - kubectl set image deployment/<your-deployment-name> <container-name>=$REPOSITORY_URI:lastest
      # - kubectl rollout restart deployment/<your-deployment-name>